services:
  front:
    image: olympic-games-starter
    ports:
      - "1974:80"

  back:
    image: workshop-organizer
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/workshopsdb"
      SPRING_DATASOURCE_USERNAME: workshops_user
      SPRING_DATASOURCE_PASSWORD: oc2024

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: workshops_user
      POSTGRES_PASSWORD: oc2024
      POSTGRES_DB: workshopsdb
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
